# Generated by Django 4.0.6 on 2022-07-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tag_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statud',
            new_name='status',
        ),
    ]
