# Generated by Django 4.0.6 on 2022-07-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
    ]
