# Generated by Django 4.0.6 on 2022-07-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img_profile',
            field=models.ImageField(blank=True, default='', null=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
