# Generated by Django 4.0.6 on 2022-07-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customer_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img_profile',
            field=models.ImageField(blank=True, default='default/person.jpeg', null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
