# Generated by Django 4.0.6 on 2022-07-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customer_img_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='img_profile',
            new_name='profile_pic',
        ),
    ]
