# Generated by Django 4.0.6 on 2022-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customer_profile_pic_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img/person.jpeg', null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
